language: node_js

node_js: node

dist: bionic

install:
 - npm install -g renovate

script:
 - renovate-config-validator

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
    branch: master